#!/bin/bash

ado="Azure DevOps"
gh='Github'

pipeline=""
token=""
prompt="Enter the Pipeline ('$ado' or '$gh'): "

while [[ 
    "$pipeline" != "$ado" && 
    "$pipeline" != "$gh" ]]; do
    read -p "$prompt" pipeline
done

if [[ "$pipeline" == "$ado" ]]; then
    while [[ -z "$token" ]]; do
        read -s -p "Enter pat token: " token
    done 
    echo "PIPELINE_PROVIDER=\"$ado\"
PAT_TOKEN=\"$token\"" > .env
elif [[ "$pipeline" == "$gh" ]]; then
    while [[ -z "$token" ]]; do
        read -s -p "Enter API token: " token
    done 
    echo "PIPELINE_PROVIDER=\"$gh\"
GH_TOKEN=\"$token\"" > .env
fi